name: Go CI

on:
  push:
    branches: [ "main" ]  # Trigger on every push to main
  pull_request:
    branches: [ "**" ]  # Trigger on all PRs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'
        cache: true # Speeds up subsequent runs by caching dependencies

    - name: Install dependencies
      run: go mod download

    - name: Verify Build
      run: go build -v ./cmd/siredmond

    - name: Run Tests
      run: go test -v ./...
